import React, { useEffect, useState } from 'react';
import {
  View,
  TextInput,
  Image,
  TouchableOpacity,
  StyleSheet,
  
  Alert,
  Keyboard,
  Platform,
} from 'react-native';
import imageIndex from '../../../../assets/imageIndex';
import { Color } from '../../../../theme/color';
import { CustomStatusBar, HeaderCustom, SuccessMessageCustom } from '../../../../component';
import ScreenNameEnum from '../../../../routes/screenName.enum';
import { useNavigation } from '@react-navigation/native';
import useSignup from '../../../Auth/signup/useSignup';
import CreateGroupName from '../../../../component/modal/GroupMemberModal/CreateGroupName';
import SelectFriendCom from '../../../../component/common/SelectFriendCom/SelectFriendCom';
import { useSelector } from 'react-redux';
import { RootState } from '../../../../redux/store';
import { createGroup, getGroupActivities, getGroupMembers } from '../../../../redux/Api/GroupApi';
import { SafeAreaView } from 'react-native-safe-area-context';
const CreateGroupScreen = () => {
  const { setToestMess, toestMess } = useSignup();
  const token = useSelector((state: RootState) => state.auth.token);
  const navigation = useNavigation();
  const [loder, setloder] = useState(false);
  const [groupNameState, setGroupNameState] = useState('');
  const [selectedMembers, setSelectedMembers] = useState<Member[]>([]);
  const [isAutoGenerated, setIsAutoGenerated] = useState(true); // Track auto-name
  const [isKeyboardVisible, setKeyboardVisible] = useState(false);
  const [isSearchFocused, setSearchFocused] = useState(false);
  const [toastMessage, setToastMessage] = useState('');
  const [toestMessColorGreen, setToestMessColorGreen] = useState(true);
  const [groupsData, setGroupsData] = useState([]);
  const [loadingGroups, setLoadingGroups] = useState(true); // optional
  const [group_Id, setGroup_Id] = useState(null); // optional
  const [group_api_create, setGroup_api_create] = useState(false); // optional

  const showToast = (message: string, isSuccess: boolean = true) => {
    setToastMessage(message);
    setToestMessColorGreen(isSuccess);
    setToestMess(true);
    setTimeout(() => {
      setToestMess(false);
    }, 2000);
  };

  useEffect(() => {
    const showSub = Keyboard.addListener('keyboardDidShow', () => setKeyboardVisible(true));
    const hideSub = Keyboard.addListener('keyboardDidHide', () => setKeyboardVisible(false));
    return () => {
      showSub.remove();
      hideSub.remove();
    };
  }, []);


  const handleCreateGroup = async () => {
    console.log("Creating group with members:", selectedMembers);
    if (!selectedMembers || selectedMembers.length === 0) {
      showToast("Please select at least one friend.", false);
      return;
    }
    const finalGroupName = groupNameState.trim().length > 0
      ? groupNameState.trim()
      : selectedMembers.length === 1
        ? selectedMembers[0].name
        : selectedMembers.length === 2
          ? `${selectedMembers[0].name} & ${selectedMembers[1].name}`
          : `${selectedMembers
            .slice(0, -1)
            .map(member => member.name || member.username)
            .join(',')} ${selectedMembers[selectedMembers.length - 1].name}`;

            console.log(finalGroupName, "finalGroupName - - ")
    setGroupNameState(finalGroupName);
    setloder(true)
    console.log(selectedMembers, "selectedMembers - - ")
    try {
      // const memberUsernames = selectedMembers.map(member => member.username); // ✅ FIXED
      const memberUsernames = selectedMembers.map(member => member.id);
      // console.log(typeof memberUsernames, "memberUsernames <-<-,-<-,------")
      // console.log(memberUsernames, "memberUsernames <-<-,-<-,------")
      const response = await createGroup(token, finalGroupName, memberUsernames);
      const createdGroupId = response?.data?.messaged?.split(' ')[0]?.trim();
      setGroup_Id(createdGroupId);
      setGroup_api_create(true);
          setloder(false)
      showToast("Group created successfully!", true);
setTimeout(() => {
  navigation.goBack();
}, 300);  
    } catch (error: any) {
                setloder(false)

      console.error("❌ Group creation failed:", error);

      if (error.response && error.response.status === 409) {
                  setloder(false)

        const errorMsg  = error.response.data.error;
        const existingGroupName   = error.response.data.existing_group_name;
          showToast(`${errorMsg} Group name: ${existingGroupName}`, false);
      } else {
                  setloder(false)

            showToast("Group creation failed. Please try again.", false);
      }
    }
  }


  useEffect(() => {
    const fetchGroupDetails = async () => {
      if (!group_api_create || !group_Id) return;

      try {
        setLoadingGroups(true);

        const groupName = groupNameState;
        console.log(group_Id, "group_Id - - -  ")
        const groupId = group_Id;
        console.log(group_Id, "grtere - --  ")
        // ✅ Fetch activities
        let activities = {
          current_page: 1,
          results: [],
          total_pages: 1,
        };
        try {
          const activityData = await getGroupActivities(token, groupId);
          activities = {
            current_page: activityData?.current_page || 2,
            results: activityData?.results || [],
            total_pages: activityData?.total_pages,
          };
        } catch (err) {
          console.warn("⚠️ Failed to fetch activities:", err.message);
        }

        // ✅ Fetch members
        let members = [];
        try {
          const memberData = await getGroupMembers(token, groupId);
          // console.log(memberData, "memberData  <----<---<--- memberData  ")
          // console.log(memberData, " typeof  memberData  <----<---<--- memberData  ")


          members = memberData?.results || [];
        } catch (err) {
          console.warn("⚠️ Failed to fetch members:", err.message);
        }

        // console.log(members, "membersmembers<----<---<--- members")
        // console.log(members, " typeof membersmembers<----<---<--- members")

        const finalGroup = {
          groupId,
          groupName,
          isMuted: false,
          members,
          activities,
        };

        setGroupsData([finalGroup]);
        console.log("✅ Final Group Data", finalGroup);

        //  Navigate after slight delay (optional)
        setTimeout(() => {
          console.log(typeof finalGroup.members, "group members typeof ---<>");
          // navigation.navigate('WatchWithFrind', {
          navigation.navigate('WatchWithFrind', {
            // group: finalGroup,
            groupProps: finalGroup,
            groupId: groupId,
            // type: 'createGroup',
          });
        }, 1000);
      } catch (err) {
        console.error("❌ Error in fetchGroupDetails:", err);
      } finally {
        setLoadingGroups(false);
      }
    };

    fetchGroupDetails();
  }, [group_api_create, group_Id]);




  // {group_api_create && (
  //   fetchGroups()
  // ) }
  // useEffect(() => {
  //   if (group_api_create && groupsData.length > 0 && group_Id) {
  //     console.log(groupsData, "<-- ✅ Navigating with final data");
  //     navigation.navigate('WatchWithFrind', {
  //       group: groupsData,
  //       groupId: group_Id,
  //       type: "createGroup", // Optional
  //     });
  //   }
  // }, [group_api_create, groupsData, group_Id]);

  // setTimeout(() => {
  //     navigation.navigate('WatchWithFrind', {

  //       group: groupsData,
  //       groupId: group_Id, // 👈 now groupId is also explicitly passed

  //       type: "createGroup"
  //     });
  //   }, 1000);

   const renderContent = () => (
    <View style={{ justifyContent: 'space-between', flex: 1, }}>

      <SelectFriendCom
        setSearchFocused={setSearchFocused}
        onSelectionChange={setSelectedMembers}
        token={token}
        type="createGroup"
      />
      {!(isSearchFocused && isKeyboardVisible) && (
        <CreateGroupName
          groupName={groupNameState}
          setGroupName={setGroupNameState}
          onClose={() => navigation.goBack()}
          onCreate={handleCreateGroup}
          showToast={showToast}
          toestMess={toestMess}
          selectedMembers={selectedMembers}
          setIsAutoGenerated={setIsAutoGenerated}
         />
      )}
    </View>
  );
  return (
    <SafeAreaView style={styles.container}>
      <CustomStatusBar />
      <View style={{ paddingTop: 18, }} >
        <HeaderCustom
          title="Add Friend to Watch+"
          backIcon={imageIndex.backArrow}
          rightIcon={false}
          onRightPress={() => navigation.navigate(ScreenNameEnum.OtherTaingPrfofile)}
        />
      </View>
      {renderContent()}
      {toestMess && (
        <SuccessMessageCustom
          textColor={Color.whiteText}
          color={toestMessColorGreen ? Color.green : Color.red}
          message={toastMessage}
        />
      )}

    </SafeAreaView>
  );
};
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.background,
  },

});

export default React.memo(CreateGroupScreen);
